package com.tservice.tserviceversion2;
// Generated 9/03/2015 11:00:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicante generated by hbm2java
 */
@Entity
@Table(name="Publicante"
    ,catalog="coswg2"
)
public class Publicante  implements java.io.Serializable {


     private int identificacion;
     private String experiencia;
     private Date fechaUltimaLicecia;
     private String nombre;
     private Date fechaNacimiento;
     private String direccion;
     private String telefono;
     private String pais;
     private String ragion;
     private String ciudad;
     private Set<Factura> facturas = new HashSet(0);
     private Set<Oferta> ofertas = new HashSet(0);

    public Publicante() {
    }

	
    public Publicante(int identificacion, String experiencia, Date fechaUltimaLicecia, String nombre, Date fechaNacimiento, String direccion, String telefono, String pais, String ragion, String ciudad) {
        this.identificacion = identificacion;
        this.experiencia = experiencia;
        this.fechaUltimaLicecia = fechaUltimaLicecia;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.telefono = telefono;
        this.pais = pais;
        this.ragion = ragion;
        this.ciudad = ciudad;
    }
    public Publicante(int identificacion, String experiencia, Date fechaUltimaLicecia, String nombre, Date fechaNacimiento, String direccion, String telefono, String pais, String ragion, String ciudad, Set<Factura> facturas, Set<Oferta> ofertas) {
       this.identificacion = identificacion;
       this.experiencia = experiencia;
       this.fechaUltimaLicecia = fechaUltimaLicecia;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.pais = pais;
       this.ragion = ragion;
       this.ciudad = ciudad;
       this.facturas = facturas;
       this.ofertas = ofertas;
    }
   
     @Id 

    
    @Column(name="Identificacion", unique=true, nullable=false)
    public int getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="Experiencia", nullable=false, length=45)
    public String getExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(String experiencia) {
        this.experiencia = experiencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaUltimaLicecia", nullable=false, length=10)
    public Date getFechaUltimaLicecia() {
        return this.fechaUltimaLicecia;
    }
    
    public void setFechaUltimaLicecia(Date fechaUltimaLicecia) {
        this.fechaUltimaLicecia = fechaUltimaLicecia;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaNacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="Direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Pais", nullable=false, length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="Ragion", nullable=false, length=45)
    public String getRagion() {
        return this.ragion;
    }
    
    public void setRagion(String ragion) {
        this.ragion = ragion;
    }

    
    @Column(name="Ciudad", nullable=false, length=45)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="publicante")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="publicante")
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


